/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ChargeRequestDTO,
  CheckRequestCreateDTO,
  CheckResultVO,
  ConsultationRequestDTO,
  ConsultationResponseVO,
  DailySummaryVO,
  DiagnosisConfirmRequestDTO,
  DiagnosisSuggestRequestDTO,
  DiagnosisSuggestResponseVO,
  DispenseRequestDTO,
  DisposalRequestCreateDTO,
  DoctorPatientListVO,
  DrugRefundRequestDTO,
  GetDailySummaryParams,
  GetDoctorsParams,
  GetDrugInventoryParams,
  GetFinanceRecordsParams,
  GetInventoryParams,
  GetOrdersParams,
  GetPatientsParams,
  GetRecordsParams,
  GetResultsParams,
  ImageAnalyzeRequestDTO,
  ImageAnalyzeResponseVO,
  InspectionRequestCreateDTO,
  LoginRequestDTO,
  LoginResponseVO,
  MedicalRecordSaveRequestDTO,
  PageResultDoctorListVO,
  PageResultDoctorPatientListVO,
  PageResultDrugInventoryVO,
  PageResultFinanceRecordVO,
  PageResultOrderListVO,
  PageResultPatientRecordListVO,
  PageResultScheduleResultVO,
  PatientAuthRegisterRequestDTO,
  PatientListVO,
  PatientLoginResponseVO,
  PatientRecordListVO,
  PatientRegisterRequestDTO,
  PrescriptionCreateDTO,
  RefundRequestDTO,
  RegisterCancelRequestDTO,
  ReportGenerateRequestDTO,
  ReportGenerateResponseVO,
  ScheduleGenerateRequestDTO,
  ScheduleGenerateResponseVO,
  SendCodeRequestDTO,
  SwitchPatientParams,
  UploadBody,
  UploadParams
} from './model';

export const getOpenAPIDefinition = () => {
const cancelRegister = <TData = AxiosResponse<void>>(
    registerCancelRequestDTO: RegisterCancelRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/patient/register/cancel`,
      registerCancelRequestDTO,options
    );
  }

const confirmDiagnosis = <TData = AxiosResponse<void>>(
    diagnosisConfirmRequestDTO: DiagnosisConfirmRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/doctor/diagnosis/confirm`,
      diagnosisConfirmRequestDTO,options
    );
  }

const switchPatient = <TData = AxiosResponse<string>>(
    params: SwitchPatientParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/patient/switch`,undefined,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const sendCode = <TData = AxiosResponse<void>>(
    sendCodeRequestDTO: SendCodeRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/patient/send-code`,
      sendCodeRequestDTO,options
    );
  }

const register = <TData = AxiosResponse<number>>(
    patientRegisterRequestDTO: PatientRegisterRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/patient/register`,
      patientRegisterRequestDTO,options
    );
  }

const logout = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/patient/logout`,undefined,options
    );
  }

const register1 = <TData = AxiosResponse<PatientLoginResponseVO>>(
    patientAuthRegisterRequestDTO: PatientAuthRegisterRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/patient/auth/register`,
      patientAuthRegisterRequestDTO,options
    );
  }

const createPrescription = <TData = AxiosResponse<number>>(
    prescriptionCreateDTO: PrescriptionCreateDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/doctor/prescription`,
      prescriptionCreateDTO,options
    );
  }

const saveMedicalRecord = <TData = AxiosResponse<void>>(
    medicalRecordSaveRequestDTO: MedicalRecordSaveRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/doctor/medical-record`,
      medicalRecordSaveRequestDTO,options
    );
  }

const createInspectionRequest = <TData = AxiosResponse<void>>(
    inspectionRequestCreateDTO: InspectionRequestCreateDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/doctor/inspection-request`,
      inspectionRequestCreateDTO,options
    );
  }

const createDisposalRequest = <TData = AxiosResponse<void>>(
    disposalRequestCreateDTO: DisposalRequestCreateDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/doctor/disposal-request`,
      disposalRequestCreateDTO,options
    );
  }

const createCheckRequest = <TData = AxiosResponse<void>>(
    checkRequestCreateDTO: CheckRequestCreateDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/doctor/check-request`,
      checkRequestCreateDTO,options
    );
  }

const sendCode1 = <TData = AxiosResponse<void>>(
    sendCodeRequestDTO: SendCodeRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/send-code`,
      sendCodeRequestDTO,options
    );
  }

const logout1 = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/logout`,undefined,options
    );
  }

const login = <TData = AxiosResponse<LoginResponseVO>>(
    loginRequestDTO: LoginRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/login`,
      loginRequestDTO,options
    );
  }

const loginByCode = <TData = AxiosResponse<LoginResponseVO>>(
    loginRequestDTO: LoginRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/login-by-code`,
      loginRequestDTO,options
    );
  }

const generate = <TData = AxiosResponse<ScheduleGenerateResponseVO>>(
    scheduleGenerateRequestDTO: ScheduleGenerateRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/ai/schedule/generate`,
      scheduleGenerateRequestDTO,options
    );
  }

const generate1 = <TData = AxiosResponse<ReportGenerateResponseVO>>(
    reportGenerateRequestDTO: ReportGenerateRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/ai/report/generate`,
      reportGenerateRequestDTO,options
    );
  }

const upload = <TData = AxiosResponse<string>>(
    uploadBody: UploadBody,
    params: UploadParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/ai/image/upload`,
      uploadBody,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const analyze = <TData = AxiosResponse<ImageAnalyzeResponseVO>>(
    imageAnalyzeRequestDTO: ImageAnalyzeRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/ai/image/analyze`,
      imageAnalyzeRequestDTO,options
    );
  }

const suggest = <TData = AxiosResponse<DiagnosisSuggestResponseVO>>(
    diagnosisSuggestRequestDTO: DiagnosisSuggestRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/ai/diagnosis/suggest`,
      diagnosisSuggestRequestDTO,options
    );
  }

const triage = <TData = AxiosResponse<ConsultationResponseVO>>(
    consultationRequestDTO: ConsultationRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/ai/consultation/triage`,
      consultationRequestDTO,options
    );
  }

const refund = <TData = AxiosResponse<void>>(
    refundRequestDTO: RefundRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/admin/finance/refund`,
      refundRequestDTO,options
    );
  }

const charge = <TData = AxiosResponse<void>>(
    chargeRequestDTO: ChargeRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/admin/finance/charge`,
      chargeRequestDTO,options
    );
  }

const drugRefund = <TData = AxiosResponse<void>>(
    drugRefundRequestDTO: DrugRefundRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/admin/drug/refund`,
      drugRefundRequestDTO,options
    );
  }

const dispense = <TData = AxiosResponse<void>>(
    dispenseRequestDTO: DispenseRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/admin/drug/dispense`,
      dispenseRequestDTO,options
    );
  }

const getRecords = <TData = AxiosResponse<PageResultPatientRecordListVO>>(
    params: GetRecordsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/patient/records`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getRecordDetail = <TData = AxiosResponse<PatientRecordListVO>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/patient/records/${id}`,options
    );
  }

const getOrders = <TData = AxiosResponse<PageResultOrderListVO>>(
    params: GetOrdersParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/patient/orders`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const list = <TData = AxiosResponse<PatientListVO[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/patient/list`,options
    );
  }

const getDoctors = <TData = AxiosResponse<PageResultDoctorListVO>>(
    params: GetDoctorsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/patient/doctors`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getInventory = <TData = AxiosResponse<PageResultDrugInventoryVO>>(
    params?: GetInventoryParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/drugstore/inventory`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getPatients = <TData = AxiosResponse<PageResultDoctorPatientListVO>>(
    params: GetPatientsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/doctor/patients`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getPatientDetail = <TData = AxiosResponse<DoctorPatientListVO>>(
    registerId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/doctor/patients/${registerId}`,options
    );
  }

const getCheckResults = <TData = AxiosResponse<CheckResultVO>>(
    registerId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/doctor/check-results/${registerId}`,options
    );
  }

const getResults = <TData = AxiosResponse<PageResultScheduleResultVO>>(
    params: GetResultsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/ai/schedule/result`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getFinanceRecords = <TData = AxiosResponse<PageResultFinanceRecordVO>>(
    params: GetFinanceRecordsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/admin/finance/records`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getDailySummary = <TData = AxiosResponse<DailySummaryVO>>(
    params: GetDailySummaryParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/admin/finance/daily-summary`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getDrugInventory = <TData = AxiosResponse<PageResultDrugInventoryVO>>(
    params: GetDrugInventoryParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/admin/drug/inventory`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

return {cancelRegister,confirmDiagnosis,switchPatient,sendCode,register,logout,register1,createPrescription,saveMedicalRecord,createInspectionRequest,createDisposalRequest,createCheckRequest,sendCode1,logout1,login,loginByCode,generate,generate1,upload,analyze,suggest,triage,refund,charge,drugRefund,dispense,getRecords,getRecordDetail,getOrders,list,getDoctors,getInventory,getPatients,getPatientDetail,getCheckResults,getResults,getFinanceRecords,getDailySummary,getDrugInventory}};
export type CancelRegisterResult = AxiosResponse<void>
export type ConfirmDiagnosisResult = AxiosResponse<void>
export type SwitchPatientResult = AxiosResponse<string>
export type SendCodeResult = AxiosResponse<void>
export type RegisterResult = AxiosResponse<number>
export type LogoutResult = AxiosResponse<void>
export type Register1Result = AxiosResponse<PatientLoginResponseVO>
export type CreatePrescriptionResult = AxiosResponse<number>
export type SaveMedicalRecordResult = AxiosResponse<void>
export type CreateInspectionRequestResult = AxiosResponse<void>
export type CreateDisposalRequestResult = AxiosResponse<void>
export type CreateCheckRequestResult = AxiosResponse<void>
export type SendCode1Result = AxiosResponse<void>
export type Logout1Result = AxiosResponse<void>
export type LoginResult = AxiosResponse<LoginResponseVO>
export type LoginByCodeResult = AxiosResponse<LoginResponseVO>
export type GenerateResult = AxiosResponse<ScheduleGenerateResponseVO>
export type Generate1Result = AxiosResponse<ReportGenerateResponseVO>
export type UploadResult = AxiosResponse<string>
export type AnalyzeResult = AxiosResponse<ImageAnalyzeResponseVO>
export type SuggestResult = AxiosResponse<DiagnosisSuggestResponseVO>
export type TriageResult = AxiosResponse<ConsultationResponseVO>
export type RefundResult = AxiosResponse<void>
export type ChargeResult = AxiosResponse<void>
export type DrugRefundResult = AxiosResponse<void>
export type DispenseResult = AxiosResponse<void>
export type GetRecordsResult = AxiosResponse<PageResultPatientRecordListVO>
export type GetRecordDetailResult = AxiosResponse<PatientRecordListVO>
export type GetOrdersResult = AxiosResponse<PageResultOrderListVO>
export type ListResult = AxiosResponse<PatientListVO[]>
export type GetDoctorsResult = AxiosResponse<PageResultDoctorListVO>
export type GetInventoryResult = AxiosResponse<PageResultDrugInventoryVO>
export type GetPatientsResult = AxiosResponse<PageResultDoctorPatientListVO>
export type GetPatientDetailResult = AxiosResponse<DoctorPatientListVO>
export type GetCheckResultsResult = AxiosResponse<CheckResultVO>
export type GetResultsResult = AxiosResponse<PageResultScheduleResultVO>
export type GetFinanceRecordsResult = AxiosResponse<PageResultFinanceRecordVO>
export type GetDailySummaryResult = AxiosResponse<DailySummaryVO>
export type GetDrugInventoryResult = AxiosResponse<PageResultDrugInventoryVO>
