/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ChargeRequestDTO,
  CheckRequestCreateDTO,
  CheckResultDetailVO,
  CheckResultVO,
  CheckinRequestDTO,
  CheckinResultVO,
  ConsultationRequestDTO,
  ConsultationResponseVO,
  DailySummaryVO,
  Department,
  DeptListVO,
  DeptQueueVO,
  DeptStatsVO,
  DiagnosisConfirmRequestDTO,
  DiagnosisSuggestRequestDTO,
  DiagnosisSuggestResponseVO,
  DispenseRequestDTO,
  DisposalRequestCreateDTO,
  DoctorPatientListVO,
  DoctorProfileVO,
  DoctorStatisticsVO,
  DoctorStatsVO,
  DrugRefundRequestDTO,
  EmployeeCreateRequestDTO,
  EmployeeListItemVO,
  GetDailySummaryParams,
  GetDoctorsParams,
  GetDrugInventoryParams,
  GetFinanceRecordsParams,
  GetInventoryParams,
  GetOrdersParams,
  GetPatientsParams,
  GetPrescriptionsParams,
  GetProfileParams,
  GetQueueCountParams,
  GetQueueDeptsParams,
  GetQueueStatusParams,
  GetRecordsParams,
  GetReportsParams,
  GetResultsParams,
  GetStatisticsParams,
  GetTodayRegistersParams,
  ImageAnalyzeRequestDTO,
  ImageAnalyzeResponseVO,
  InspectionRequestCreateDTO,
  LoginRequestDTO,
  LoginResponseVO,
  MedicalRecordSaveRequestDTO,
  MedicalTechVO,
  PageResultDoctorListVO,
  PageResultDoctorPatientListVO,
  PageResultDrugInventoryVO,
  PageResultFinanceRecordVO,
  PageResultOrderListVO,
  PageResultPatientRecordListVO,
  PageResultPrescriptionListVO,
  PageResultReportListVO,
  PageResultScheduleResultVO,
  PatientAuthRegisterRequestDTO,
  PatientCheckRequestDTO,
  PatientCurrentVO,
  PatientInspectionRequestDTO,
  PatientListVO,
  PatientLoginResponseVO,
  PatientRecordListVO,
  PatientRegisterRequestDTO,
  PrescriptionCreateDTO,
  PrescriptionDetailVO,
  QueueCountVO,
  QueueStatusVO,
  RefundRequestDTO,
  RegisterCancelRequestDTO,
  ReportDetailVO,
  ReportGenerateRequestDTO,
  ReportGenerateResponseVO,
  ScheduleGenerateRequestDTO,
  ScheduleGenerateResponseVO,
  SendCodeRequestDTO,
  SwitchPatientParams,
  TodayRegisterVO,
  UploadBody,
  UploadParams
} from './model';

export const getOpenAPIDefinition = () => {
const markReportRead = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/patient/reports/${id}/read`,undefined,options
    );
  }

const cancelRegister = <TData = AxiosResponse<void>>(
    registerCancelRequestDTO: RegisterCancelRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/patient/register/cancel`,
      registerCancelRequestDTO,options
    );
  }

const confirmDiagnosis = <TData = AxiosResponse<void>>(
    diagnosisConfirmRequestDTO: DiagnosisConfirmRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/doctor/diagnosis/confirm`,
      diagnosisConfirmRequestDTO,options
    );
  }

const switchPatient = <TData = AxiosResponse<string>>(
    params: SwitchPatientParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/patient/switch`,undefined,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const sendCode = <TData = AxiosResponse<void>>(
    sendCodeRequestDTO: SendCodeRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/patient/send-code`,
      sendCodeRequestDTO,options
    );
  }

const register = <TData = AxiosResponse<number>>(
    patientRegisterRequestDTO: PatientRegisterRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/patient/register`,
      patientRegisterRequestDTO,options
    );
  }

const logout = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/patient/logout`,undefined,options
    );
  }

const createInspectionRequest = <TData = AxiosResponse<void>>(
    patientInspectionRequestDTO: PatientInspectionRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/patient/inspection-request`,
      patientInspectionRequestDTO,options
    );
  }

const submitCheckin = <TData = AxiosResponse<CheckinResultVO>>(
    checkinRequestDTO: CheckinRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/patient/checkin/submit`,
      checkinRequestDTO,options
    );
  }

const createCheckRequest = <TData = AxiosResponse<void>>(
    patientCheckRequestDTO: PatientCheckRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/patient/check-request`,
      patientCheckRequestDTO,options
    );
  }

const register1 = <TData = AxiosResponse<PatientLoginResponseVO>>(
    patientAuthRegisterRequestDTO: PatientAuthRegisterRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/patient/auth/register`,
      patientAuthRegisterRequestDTO,options
    );
  }

const createPrescription = <TData = AxiosResponse<number>>(
    prescriptionCreateDTO: PrescriptionCreateDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/doctor/prescription`,
      prescriptionCreateDTO,options
    );
  }

const saveMedicalRecord = <TData = AxiosResponse<void>>(
    medicalRecordSaveRequestDTO: MedicalRecordSaveRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/doctor/medical-record`,
      medicalRecordSaveRequestDTO,options
    );
  }

const createInspectionRequest1 = <TData = AxiosResponse<void>>(
    inspectionRequestCreateDTO: InspectionRequestCreateDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/doctor/inspection-request`,
      inspectionRequestCreateDTO,options
    );
  }

const createDisposalRequest = <TData = AxiosResponse<void>>(
    disposalRequestCreateDTO: DisposalRequestCreateDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/doctor/disposal-request`,
      disposalRequestCreateDTO,options
    );
  }

const createCheckRequest1 = <TData = AxiosResponse<void>>(
    checkRequestCreateDTO: CheckRequestCreateDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/doctor/check-request`,
      checkRequestCreateDTO,options
    );
  }

const sendCode1 = <TData = AxiosResponse<void>>(
    sendCodeRequestDTO: SendCodeRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/send-code`,
      sendCodeRequestDTO,options
    );
  }

const logout1 = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/logout`,undefined,options
    );
  }

const login = <TData = AxiosResponse<LoginResponseVO>>(
    loginRequestDTO: LoginRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/login`,
      loginRequestDTO,options
    );
  }

const loginByCode = <TData = AxiosResponse<LoginResponseVO>>(
    loginRequestDTO: LoginRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/login-by-code`,
      loginRequestDTO,options
    );
  }

const generate = <TData = AxiosResponse<ScheduleGenerateResponseVO>>(
    scheduleGenerateRequestDTO: ScheduleGenerateRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/ai/schedule/generate`,
      scheduleGenerateRequestDTO,options
    );
  }

const generate1 = <TData = AxiosResponse<ReportGenerateResponseVO>>(
    reportGenerateRequestDTO: ReportGenerateRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/ai/report/generate`,
      reportGenerateRequestDTO,options
    );
  }

const upload = <TData = AxiosResponse<string>>(
    uploadBody: UploadBody,
    params: UploadParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/ai/image/upload`,
      uploadBody,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const analyze = <TData = AxiosResponse<ImageAnalyzeResponseVO>>(
    imageAnalyzeRequestDTO: ImageAnalyzeRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/ai/image/analyze`,
      imageAnalyzeRequestDTO,options
    );
  }

const suggest = <TData = AxiosResponse<DiagnosisSuggestResponseVO>>(
    diagnosisSuggestRequestDTO: DiagnosisSuggestRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/ai/diagnosis/suggest`,
      diagnosisSuggestRequestDTO,options
    );
  }

const triage = <TData = AxiosResponse<ConsultationResponseVO>>(
    consultationRequestDTO: ConsultationRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/ai/consultation/triage`,
      consultationRequestDTO,options
    );
  }

const refund = <TData = AxiosResponse<void>>(
    refundRequestDTO: RefundRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/admin/finance/refund`,
      refundRequestDTO,options
    );
  }

const charge = <TData = AxiosResponse<void>>(
    chargeRequestDTO: ChargeRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/admin/finance/charge`,
      chargeRequestDTO,options
    );
  }

const createEmployee = <TData = AxiosResponse<number>>(
    employeeCreateRequestDTO: EmployeeCreateRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/admin/employee/create`,
      employeeCreateRequestDTO,options
    );
  }

const drugRefund = <TData = AxiosResponse<void>>(
    drugRefundRequestDTO: DrugRefundRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/admin/drug/refund`,
      drugRefundRequestDTO,options
    );
  }

const dispense = <TData = AxiosResponse<void>>(
    dispenseRequestDTO: DispenseRequestDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/admin/drug/dispense`,
      dispenseRequestDTO,options
    );
  }

const getReports = <TData = AxiosResponse<PageResultReportListVO>>(
    params: GetReportsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/patient/reports`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getReportDetail = <TData = AxiosResponse<ReportDetailVO>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/patient/reports/${id}`,options
    );
  }

const getTodayRegisters = <TData = AxiosResponse<TodayRegisterVO[]>>(
    params: GetTodayRegistersParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/patient/register/today`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getRecords = <TData = AxiosResponse<PageResultPatientRecordListVO>>(
    params: GetRecordsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/patient/records`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getRecordDetail = <TData = AxiosResponse<PatientRecordListVO>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/patient/records/${id}`,options
    );
  }

const getQueueStatus = <TData = AxiosResponse<QueueStatusVO>>(
    params: GetQueueStatusParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/patient/queue/status`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getQueueDepts = <TData = AxiosResponse<DeptQueueVO[]>>(
    params: GetQueueDeptsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/patient/queue/depts`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getQueueCount = <TData = AxiosResponse<QueueCountVO>>(
    params: GetQueueCountParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/patient/queue/count`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getPrescriptions = <TData = AxiosResponse<PageResultPrescriptionListVO>>(
    params: GetPrescriptionsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/patient/prescriptions`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getPrescriptionDetail = <TData = AxiosResponse<PrescriptionDetailVO>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/patient/prescriptions/${id}`,options
    );
  }

const getOrders = <TData = AxiosResponse<PageResultOrderListVO>>(
    params: GetOrdersParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/patient/orders`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getInspectionList = <TData = AxiosResponse<MedicalTechVO[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/patient/medical-technology/inspection`,options
    );
  }

const getCheckList = <TData = AxiosResponse<MedicalTechVO[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/patient/medical-technology/check`,options
    );
  }

const list = <TData = AxiosResponse<PatientListVO[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/patient/list`,options
    );
  }

const getDoctors = <TData = AxiosResponse<PageResultDoctorListVO>>(
    params: GetDoctorsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/patient/doctors`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const listDepartments = <TData = AxiosResponse<DeptListVO[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/patient/department/list`,options
    );
  }

const getCurrentPatient = <TData = AxiosResponse<PatientCurrentVO>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/patient/current`,options
    );
  }

const getInventory = <TData = AxiosResponse<PageResultDrugInventoryVO>>(
    params?: GetInventoryParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/drugstore/inventory`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getStatistics = <TData = AxiosResponse<DoctorStatisticsVO>>(
    params: GetStatisticsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/doctor/statistics`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getProfile = <TData = AxiosResponse<DoctorProfileVO>>(
    params: GetProfileParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/doctor/profile`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getPatients = <TData = AxiosResponse<PageResultDoctorPatientListVO>>(
    params: GetPatientsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/doctor/patients`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getPatientDetail = <TData = AxiosResponse<DoctorPatientListVO>>(
    registerId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/doctor/patients/${registerId}`,options
    );
  }

const getCheckResults = <TData = AxiosResponse<CheckResultVO>>(
    registerId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/doctor/check-results/${registerId}`,options
    );
  }

const getCheckResultDetail = <TData = AxiosResponse<CheckResultDetailVO>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/doctor/check-result/${id}`,options
    );
  }

const getResults = <TData = AxiosResponse<PageResultScheduleResultVO>>(
    params: GetResultsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/ai/schedule/result`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getDoctorStats = <TData = AxiosResponse<DoctorStatsVO[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/admin/statistics/doctor`,options
    );
  }

const getDeptStats = <TData = AxiosResponse<DeptStatsVO[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/admin/statistics/dept`,options
    );
  }

const getFinanceRecords = <TData = AxiosResponse<PageResultFinanceRecordVO>>(
    params: GetFinanceRecordsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/admin/finance/records`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getDailySummary = <TData = AxiosResponse<DailySummaryVO>>(
    params: GetDailySummaryParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/admin/finance/daily-summary`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const listEmployees = <TData = AxiosResponse<EmployeeListItemVO[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/admin/employee/list`,options
    );
  }

const listDoctors = <TData = AxiosResponse<EmployeeListItemVO[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/admin/employee/doctors`,options
    );
  }

const getDrugInventory = <TData = AxiosResponse<PageResultDrugInventoryVO>>(
    params: GetDrugInventoryParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/admin/drug/inventory`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const listDepartments1 = <TData = AxiosResponse<Department[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/admin/department/list`,options
    );
  }

return {markReportRead,cancelRegister,confirmDiagnosis,switchPatient,sendCode,register,logout,createInspectionRequest,submitCheckin,createCheckRequest,register1,createPrescription,saveMedicalRecord,createInspectionRequest1,createDisposalRequest,createCheckRequest1,sendCode1,logout1,login,loginByCode,generate,generate1,upload,analyze,suggest,triage,refund,charge,createEmployee,drugRefund,dispense,getReports,getReportDetail,getTodayRegisters,getRecords,getRecordDetail,getQueueStatus,getQueueDepts,getQueueCount,getPrescriptions,getPrescriptionDetail,getOrders,getInspectionList,getCheckList,list,getDoctors,listDepartments,getCurrentPatient,getInventory,getStatistics,getProfile,getPatients,getPatientDetail,getCheckResults,getCheckResultDetail,getResults,getDoctorStats,getDeptStats,getFinanceRecords,getDailySummary,listEmployees,listDoctors,getDrugInventory,listDepartments1}};
export type MarkReportReadResult = AxiosResponse<void>
export type CancelRegisterResult = AxiosResponse<void>
export type ConfirmDiagnosisResult = AxiosResponse<void>
export type SwitchPatientResult = AxiosResponse<string>
export type SendCodeResult = AxiosResponse<void>
export type RegisterResult = AxiosResponse<number>
export type LogoutResult = AxiosResponse<void>
export type CreateInspectionRequestResult = AxiosResponse<void>
export type SubmitCheckinResult = AxiosResponse<CheckinResultVO>
export type CreateCheckRequestResult = AxiosResponse<void>
export type Register1Result = AxiosResponse<PatientLoginResponseVO>
export type CreatePrescriptionResult = AxiosResponse<number>
export type SaveMedicalRecordResult = AxiosResponse<void>
export type CreateInspectionRequest1Result = AxiosResponse<void>
export type CreateDisposalRequestResult = AxiosResponse<void>
export type CreateCheckRequest1Result = AxiosResponse<void>
export type SendCode1Result = AxiosResponse<void>
export type Logout1Result = AxiosResponse<void>
export type LoginResult = AxiosResponse<LoginResponseVO>
export type LoginByCodeResult = AxiosResponse<LoginResponseVO>
export type GenerateResult = AxiosResponse<ScheduleGenerateResponseVO>
export type Generate1Result = AxiosResponse<ReportGenerateResponseVO>
export type UploadResult = AxiosResponse<string>
export type AnalyzeResult = AxiosResponse<ImageAnalyzeResponseVO>
export type SuggestResult = AxiosResponse<DiagnosisSuggestResponseVO>
export type TriageResult = AxiosResponse<ConsultationResponseVO>
export type RefundResult = AxiosResponse<void>
export type ChargeResult = AxiosResponse<void>
export type CreateEmployeeResult = AxiosResponse<number>
export type DrugRefundResult = AxiosResponse<void>
export type DispenseResult = AxiosResponse<void>
export type GetReportsResult = AxiosResponse<PageResultReportListVO>
export type GetReportDetailResult = AxiosResponse<ReportDetailVO>
export type GetTodayRegistersResult = AxiosResponse<TodayRegisterVO[]>
export type GetRecordsResult = AxiosResponse<PageResultPatientRecordListVO>
export type GetRecordDetailResult = AxiosResponse<PatientRecordListVO>
export type GetQueueStatusResult = AxiosResponse<QueueStatusVO>
export type GetQueueDeptsResult = AxiosResponse<DeptQueueVO[]>
export type GetQueueCountResult = AxiosResponse<QueueCountVO>
export type GetPrescriptionsResult = AxiosResponse<PageResultPrescriptionListVO>
export type GetPrescriptionDetailResult = AxiosResponse<PrescriptionDetailVO>
export type GetOrdersResult = AxiosResponse<PageResultOrderListVO>
export type GetInspectionListResult = AxiosResponse<MedicalTechVO[]>
export type GetCheckListResult = AxiosResponse<MedicalTechVO[]>
export type ListResult = AxiosResponse<PatientListVO[]>
export type GetDoctorsResult = AxiosResponse<PageResultDoctorListVO>
export type ListDepartmentsResult = AxiosResponse<DeptListVO[]>
export type GetCurrentPatientResult = AxiosResponse<PatientCurrentVO>
export type GetInventoryResult = AxiosResponse<PageResultDrugInventoryVO>
export type GetStatisticsResult = AxiosResponse<DoctorStatisticsVO>
export type GetProfileResult = AxiosResponse<DoctorProfileVO>
export type GetPatientsResult = AxiosResponse<PageResultDoctorPatientListVO>
export type GetPatientDetailResult = AxiosResponse<DoctorPatientListVO>
export type GetCheckResultsResult = AxiosResponse<CheckResultVO>
export type GetCheckResultDetailResult = AxiosResponse<CheckResultDetailVO>
export type GetResultsResult = AxiosResponse<PageResultScheduleResultVO>
export type GetDoctorStatsResult = AxiosResponse<DoctorStatsVO[]>
export type GetDeptStatsResult = AxiosResponse<DeptStatsVO[]>
export type GetFinanceRecordsResult = AxiosResponse<PageResultFinanceRecordVO>
export type GetDailySummaryResult = AxiosResponse<DailySummaryVO>
export type ListEmployeesResult = AxiosResponse<EmployeeListItemVO[]>
export type ListDoctorsResult = AxiosResponse<EmployeeListItemVO[]>
export type GetDrugInventoryResult = AxiosResponse<PageResultDrugInventoryVO>
export type ListDepartments1Result = AxiosResponse<Department[]>
