"""Configuration facade for RAG components."""

from __future__ import annotations

try:
    from .. import config as app_config
except ImportError:  # pragma: no cover - direct script fallback.
    import config as app_config  # type: ignore


RAG_ENABLED = app_config.RAG_ENABLED
RAG_VECTOR_BACKEND = app_config.RAG_VECTOR_BACKEND
RAG_DB_DSN = app_config.RAG_DB_DSN
RAG_STRICT_MODE = app_config.RAG_STRICT_MODE
RAG_TOP_K = app_config.RAG_TOP_K
RAG_RECALL_TOP_N = app_config.RAG_RECALL_TOP_N
RAG_MIN_SIMILARITY = app_config.RAG_MIN_SIMILARITY
RAG_EMBEDDING_DIM = app_config.RAG_EMBEDDING_DIM
RAG_EMBEDDING_PROVIDER = app_config.RAG_EMBEDDING_PROVIDER
RAG_HNSW_EF_SEARCH = app_config.RAG_HNSW_EF_SEARCH
RAG_RERANK_ENABLED = app_config.RAG_RERANK_ENABLED
RAG_RERANK_PROVIDER = app_config.RAG_RERANK_PROVIDER
RAG_RERANK_TOP_N = app_config.RAG_RERANK_TOP_N
RAG_RERANK_TIMEOUT_SECONDS = app_config.RAG_RERANK_TIMEOUT_SECONDS
RAG_CHUNK_MAX_CHARS = app_config.RAG_CHUNK_MAX_CHARS
RAG_CHUNK_OVERLAP_CHARS = app_config.RAG_CHUNK_OVERLAP_CHARS
DEPLOY_ENV = app_config.DEPLOY_ENV
REDIS_ENABLED = app_config.REDIS_ENABLED
REDIS_URL = app_config.REDIS_URL
REDIS_CONNECT_TIMEOUT_SECONDS = app_config.REDIS_CONNECT_TIMEOUT_SECONDS
REDIS_SOCKET_TIMEOUT_SECONDS = app_config.REDIS_SOCKET_TIMEOUT_SECONDS
CACHE_RAG_RETRIEVAL_TTL_SECONDS = app_config.CACHE_RAG_RETRIEVAL_TTL_SECONDS
CACHE_LLM_RESPONSE_TTL_SECONDS = app_config.CACHE_LLM_RESPONSE_TTL_SECONDS
CACHE_MODEL_RESULT_TTL_SECONDS = app_config.CACHE_MODEL_RESULT_TTL_SECONDS
CACHE_PROJECT2_DICT_TTL_SECONDS = app_config.CACHE_PROJECT2_DICT_TTL_SECONDS
DASHSCOPE_API_KEY = app_config.DASHSCOPE_API_KEY
DASHSCOPE_EMBEDDING_BASE_URL = app_config.DASHSCOPE_EMBEDDING_BASE_URL
DASHSCOPE_EMBEDDING_MODEL = app_config.DASHSCOPE_EMBEDDING_MODEL
DASHSCOPE_EMBEDDING_TIMEOUT_SECONDS = app_config.DASHSCOPE_EMBEDDING_TIMEOUT_SECONDS
DASHSCOPE_RERANK_BASE_URL = app_config.DASHSCOPE_RERANK_BASE_URL
DASHSCOPE_RERANK_MODEL = app_config.DASHSCOPE_RERANK_MODEL

LLM_ENABLED = app_config.LLM_ENABLED
LLM_PROVIDER = app_config.LLM_PROVIDER
LLM_STRICT_MODE = app_config.LLM_STRICT_MODE
ALI_BAILIAN_API_KEY = app_config.ALI_BAILIAN_API_KEY
ALI_BAILIAN_BASE_URL = app_config.ALI_BAILIAN_BASE_URL
ALI_BAILIAN_MODEL = app_config.ALI_BAILIAN_MODEL
ALI_BAILIAN_TIMEOUT_SECONDS = app_config.ALI_BAILIAN_TIMEOUT_SECONDS
