/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Annotation {
  x?: number;
  y?: number;
  width?: number;
  height?: number;
  label?: string;
}
