/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ChargeItem {
  id?: number;
  sourceId?: number;
  sourceType?: string;
  registerId?: number;
  itemName?: string;
  itemType?: string;
  amount?: number;
  status?: string;
  financeRecordId?: number;
  chargeMethod?: string;
  chargeTime?: string;
  refundReason?: string;
  refundTime?: string;
  operatorId?: number;
  createTime?: string;
  updateTime?: string;
}
