/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ChargeRequestDTO {
  registerId: number;
  itemIds: number[];
  chargeMethod: string;
  /**
   * @minimum 0.01
   */
  amount?: number;
}
