/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CheckItemDTO } from './checkItemDTO';

export interface CheckRequestCreateDTO {
  registerId: number;
  items: CheckItemDTO[];
}
