/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CheckRequest {
  id?: number;
  registerId?: number;
  medicalTechnologyId?: number;
  checkInfo?: string;
  checkPosition?: string;
  creationTime?: string;
  checkEmployeeId?: number;
  inputcheckEmployeeId?: number;
  checkTime?: string;
  checkResult?: string;
  checkState?: string;
  checkRemark?: string;
}
