/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CheckResultDetailVO {
  id?: number;
  checkInfo?: string;
  checkPosition?: string;
  checkState?: string;
  checkResult?: string;
  checkRemark?: string;
  createTime?: string;
  checkTime?: string;
  aiFindings?: string;
  aiConclusion?: string;
  aiConfidence?: number;
}
