/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CheckRequest } from './checkRequest';
import type { InspectionRequest } from './inspectionRequest';
import type { DisposalRequest } from './disposalRequest';

export interface CheckResultVO {
  checkRequests?: CheckRequest[];
  inspectionRequests?: InspectionRequest[];
  disposalRequests?: DisposalRequest[];
}
