/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DeptRecommendation } from './deptRecommendation';

export interface ConsultationResponseVO {
  consultationId?: number;
  recommendations?: DeptRecommendation[];
}
