/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface DailySummaryVO {
  summaryDate?: string;
  totalTransactions?: number;
  totalAmount?: number;
  refundAmount?: number;
  chargeCount?: number;
  refundCount?: number;
  operatorName?: string;
}
