/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ShiftInfo } from './shiftInfo';

export interface DailySchedule {
  date?: string;
  morning?: ShiftInfo[];
  afternoon?: ShiftInfo[];
}
