/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Department {
  id?: number;
  deptCode?: string;
  deptName?: string;
  deptType?: string;
  delmark?: boolean;
  createTime?: string;
  updateTime?: string;
}
