/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface DeptRecommendation {
  deptId?: number;
  deptName?: string;
  confidence?: number;
  reason?: string;
}
