/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface DeptStatsVO {
  id?: number;
  name?: string;
  icon?: string;
  doctorCount?: number;
  visits?: number;
  revisitRate?: number;
  avgRating?: number;
  status?: string;
  saturation?: number;
}
