/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface DisposalRequest {
  id?: number;
  registerId?: number;
  medicalTechnologyId?: number;
  disposalInfo?: string;
  disposalPosition?: string;
  creationTime?: string;
  disposalEmployeeId?: number;
  inputdisposalEmployeeId?: number;
  disposalTime?: string;
  disposalResult?: string;
  disposalState?: string;
  disposalRemark?: string;
}
