/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface DoctorStatisticsVO {
  todayVisits?: number;
  monthVisits?: number;
  totalVisits?: number;
  pendingCount?: number;
  consultingCount?: number;
  finishedCount?: number;
}
