/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface DoctorStatsVO {
  id?: number;
  name?: string;
  dept?: string;
  title?: string;
  visits?: number;
  revisitRate?: number;
}
