/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface DoctorListQueryDTO {
  /** @minimum 1 */
  pageNum?: number;
  /**
   * @minimum 1
   * @maximum 10000
   */
  pageSize?: number;
  deptId: number;
  visitDate?: string;
  noon?: string;
}
