/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface DoctorListVO {
  doctorId?: number;
  deptId?: number;
  deptName?: string;
  doctorName?: string;
  titleLevel?: string;
  specialty?: string;
  scheduleDate?: string;
  noon?: string;
  registQuota?: number;
  remainingQuota?: number;
}
