/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface DoctorPatientListVO {
  registerId?: number;
  caseNumber?: string;
  patientName?: string;
  gender?: string;
  age?: number;
  registrationTime?: string;
  noon?: string;
}
