/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface DoctorProfileVO {
  id?: number;
  realname?: string;
  titleLevel?: string;
  phone?: string;
  roleType?: string;
  deptmentId?: number;
  deptName?: string;
  delmark?: boolean;
  createTime?: string;
}
