/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface DrugInventoryVO {
  drugId?: number;
  drugCode?: string;
  drugName?: string;
  drugFormat?: string;
  drugUnit?: string;
  stockNum?: number;
  drugPrice?: number;
  alert?: boolean;
  manufacturer?: string;
}
