/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface FinanceRecordVO {
  id?: number;
  recordNo?: string;
  registerId?: number;
  patientName?: string;
  itemType?: string;
  itemName?: string;
  amount?: number;
  chargeMethod?: string;
  recordType?: string;
  createTime?: string;
  operatorName?: string;
}
