/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface FinanceRecordsQueryDTO {
  /** @minimum 1 */
  pageNum?: number;
  /**
   * @minimum 1
   * @maximum 50
   */
  pageSize?: number;
  startDate?: string;
  endDate?: string;
  chargeMethod?: string;
  recordType?: string;
}
