/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DailySummaryQueryDTO } from './dailySummaryQueryDTO';

export type GetDailySummaryParams = {
query: DailySummaryQueryDTO;
};
