/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ReportQueryDTO } from './reportQueryDTO';

export type GetReportsParams = {
query: ReportQueryDTO;
};
