/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Annotation } from './annotation';

export interface ImageAnalyzeResponseVO {
  analysisId?: number;
  findings?: string;
  conclusion?: string;
  confidence?: number;
  positiveProbability?: number;
  subtypeProbabilities?: Record<string, number>;
  analysisReliability?: string;
  modelLimitations?: string[];
  annotations?: Annotation[];
  aiImagingStatus?: Record<string, any>;
  previewUrls?: Record<string, string>;
}
