/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface InspectionRequest {
  id?: number;
  registerId?: number;
  medicalTechnologyId?: number;
  inspectionInfo?: string;
  inspectionPosition?: string;
  creationTime?: string;
  inspectionEmployeeId?: number;
  inputinspectionEmployeeId?: number;
  inspectionTime?: string;
  inspectionResult?: string;
  inspectionState?: string;
  inspectionRemark?: string;
  isSelfBooked?: number;
  bookedTime?: string;
}
