/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { InspectionItemDTO } from './inspectionItemDTO';

export interface InspectionRequestCreateDTO {
  registerId: number;
  items: InspectionItemDTO[];
}
