/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface LoginRequestDTO {
  /** @pattern ^1[3-9]\d{9}$ */
  phone?: string;
  username?: string;
  /**
   * @minLength 6
   * @maxLength 20
   */
  password?: string;
  /**
   * @minLength 4
   * @maxLength 6
   */
  verifyCode?: string;
  loginType: string;
}
