/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface MedicalRecordSaveRequestDTO {
  registerId: number;
  /**
   * @minLength 0
   * @maxLength 200
   */
  readme?: string;
  /**
   * @minLength 0
   * @maxLength 500
   */
  present?: string;
  presentTreat?: string;
  history?: string;
  allergy?: string;
  physique?: string;
  /**
   * @minLength 0
   * @maxLength 500
   */
  proposal?: string;
  careful?: string;
  diagnosis?: string;
}
