/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface MedicalTechVO {
  id?: number;
  name?: string;
  type?: string;
  typeName?: string;
  bodyPart?: string;
  price?: number;
  tips?: string;
}
