/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderListVO } from './orderListVO';

export interface PageResultOrderListVO {
  total?: number;
  pageNum?: number;
  pageSize?: number;
  totalPages?: number;
  records?: OrderListVO[];
}
