/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { FinanceRecordVO } from './financeRecordVO';

export interface PageResultFinanceRecordVO {
  total?: number;
  pageNum?: number;
  pageSize?: number;
  totalPages?: number;
  records?: FinanceRecordVO[];
}
