/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PatientRecordListVO } from './patientRecordListVO';

export interface PageResultPatientRecordListVO {
  total?: number;
  pageNum?: number;
  pageSize?: number;
  totalPages?: number;
  records?: PatientRecordListVO[];
}
