/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DoctorListVO } from './doctorListVO';

export interface PageResultDoctorListVO {
  total?: number;
  pageNum?: number;
  pageSize?: number;
  totalPages?: number;
  records?: DoctorListVO[];
}
