/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PatientRegisterRequestDTO {
  patientId: number;
  deptId: number;
  doctorId: number;
  visitDate: string;
  noon: string;
  registLevelId?: number;
  settleCategoryId?: number;
  registMethod?: string;
}
