/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PatientListVO {
  id?: number;
  caseNumber?: string;
  realName?: string;
  gender?: string;
  phone?: string;
  isDefault?: boolean;
  cardNumber?: string;
  birthdate?: string;
  homeAddress?: string;
  relation?: string;
  age?: number;
}
