/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PatientRecordListVO {
  registerId?: number;
  visitDate?: string;
  deptName?: string;
  doctorName?: string;
  diagnosis?: string;
  visitState?: string;
  visitStateName?: string;
  noon?: string;
  queueNumber?: number;
  checkinStatus?: number;
  registFee?: number;
  deptId?: number;
  doctorId?: number;
  patientName?: string;
  gender?: string;
  age?: number;
  allergyHistory?: string;
  caseNumber?: string;
}
