/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PatientCheckRequestDTO {
  registerId: number;
  patientId: number;
  medicalTechnologyIds: number[];
  bookedTime: string;
}
