/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PatientAuthRegisterRequestDTO {
  realName: string;
  /** @pattern ^\d{17}[\dXx]$ */
  cardNumber: string;
  /** @pattern ^1[3-9]\d{9}$ */
  phone: string;
  code: string;
  gender?: string;
  birthdate?: string;
  homeAddress?: string;
}
