/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PatientRegisterRequestDTO {
  /**
   * @minLength 0
   * @maxLength 64
   */
  realName: string;
  /** @pattern ^(男|女)$ */
  gender: string;
  /** @pattern ^\d{17}[\dXx]$ */
  cardNumber: string;
  birthdate: string;
  homeAddress: string;
  phone?: string;
  deptId: number;
  doctorId: number;
  visitDate: string;
  noon: string;
  registLevelId: number;
  settleCategoryId: number;
  registMethod?: string;
}
