/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PendingCheckRequestVO {
  id?: number;
  registerId?: number;
  medicalTechnologyId?: number;
  techName?: string;
  checkInfo?: string;
  checkPosition?: string;
  techPrice?: number;
  creationTime?: string;
}
