/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PrescriptionDrugDetailVO {
  drugId?: number;
  drugName?: string;
  specification?: string;
  dosage?: string;
  frequency?: string;
  days?: number;
  quantity?: number;
  price?: number;
}
