/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PrescriptionItemDTO {
  drugId: number;
  usageRoute: string;
  frequency: string;
  dosage: string;
  singleDose?: string;
  /**
   * @minimum 1
   * @maximum 90
   */
  useDays?: number;
  /**
   * @minimum 1
   * @maximum 999
   */
  drugNumber?: number;
}
