/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PrescriptionRefundVO {
  prescriptionId?: number;
  prescriptionNo?: string;
  patientName?: string;
  drugList?: string[];
  totalAmount?: number;
  status?: string;
}
