/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PrescriptionDrugSummaryVO } from './prescriptionDrugSummaryVO';

export interface PrescriptionListVO {
  id?: number;
  prescriptionNo?: string;
  deptName?: string;
  doctorName?: string;
  patientName?: string;
  status?: string;
  totalAmount?: number;
  creationTime?: string;
  drugs?: PrescriptionDrugSummaryVO[];
}
