/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Prescription {
  id?: number;
  registerId?: number;
  doctorId?: number;
  prescriptionNo?: string;
  totalAmount?: number;
  prescriptionStatus?: string;
  creationTime?: string;
  updateTime?: string;
  dispenseTime?: string;
  pharmacistId?: number;
}
