/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PrescriptionItemDTO } from './prescriptionItemDTO';

export interface PrescriptionCreateDTO {
  registerId: number;
  doctorId: number;
  items: PrescriptionItemDTO[];
}
