/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { QueueItemVO } from './queueItemVO';

export interface QueueStatusVO {
  queueNumber?: string;
  aheadCount?: number;
  currentCalling?: string;
  currentRoom?: string;
  deptName?: string;
  queueList?: QueueItemVO[];
}
