/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RefundRequestDTO {
  registerId: number;
  itemIds: number[];
  itemTypes?: string[];
  /**
   * @minimum 0.01
   */
  refundAmount?: number;
  refundReason?: string;
}
