/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ReportDetailVO {
  id?: number;
  reportTitle?: string;
  requestType?: string;
  requestTypeName?: string;
  deptName?: string;
  patientName?: string;
  reportTime?: string;
  reportText?: string;
  isViewed?: boolean;
  reportFileUrl?: string;
}
