/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ScheduleResultVO {
  doctorId?: number;
  doctorName?: string;
  scheduleDate?: string;
  shiftType?: string;
  registQuota?: number;
}
