/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface SendCodeRequestDTO {
  /** @pattern ^1[3-9]\d{9}$ */
  phone: string;
  codeType: string;
}
