/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Suggestion {
  diseaseName?: string;
  diseaseCode?: string;
  confidence?: number;
  evidence?: string;
}
