/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TodayRegisterVO {
  registerId?: number;
  deptName?: string;
  doctorName?: string;
  visitDate?: string;
  noon?: string;
  location?: string;
  patientName?: string;
  checkinStatus?: number;
}
